name: Trigger auto deployment for hello-westeu-dev

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/hello-westeu-dev-AutoDeployTrigger-146f231c-ebb0-4db0-81a2-5fac236b77ca.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.HELLOWESTEUDEV_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: codebreakerphkj7iq57pwlcdev.azurecr.io
          registryUsername: ${{ secrets.HELLOWESTEUDEV_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HELLOWESTEUDEV_REGISTRY_PASSWORD }}
          containerAppName: hello-westeu-dev
          resourceGroup: rg-codebreaker-dev
          imageToBuild: codebreakerphkj7iq57pwlcdev.azurecr.io/hello-westeu-dev:${{ github.sha }}
          

     

